### ISSUE TITLE
[parent issue] improve developer experience

### ISSUE THREAD

**Issue by leloykun** [noi-ph/hurado#33]
### Admin stuff
- [ ] Add a branch protection rule that requires at least one approval from a reviewer before merging
- [ ] Limit who can review to only the admins or more experienced contributors
- [ ] (optional) Make @leloykun an admin

### Visibility
- [ ] Sync the repo to the #online-judge channel in NOI-PH's Discord server (so we get alerted every time someone submits a pull request or something)

### Tests
- [ ] Add tests
- [ ] Add github actions that run the tests on pull request / push. Preferably we have separate github actions for `web-client` & `web-server` so we can limit which tests we run based on the contents of the PR

### Developer Experience
- [ ] Add pre-commit hooks
- [ ] Add github actions that run linters such as eslint & black and typechecks that get run on pull request / every push
- [ ] Add a script that runs `web-client` / `web-server`. Perhaps with an interface like `./run.sh client` & `./run.sh server`

### Docs
- [x] Clean up the readme
- [x] Add instructions on how to deploy this to the cloud

**Comment by jabbawookiees** [comment]
Happy to accept PRs towards fixing these issues :)
